language: node_js
node_js:
  - "7"

sudo: required

script:
  - strace ./node_modules/.bin/tsc -p bad-test-case/proj1/tsconfig.json &> strace.log
  - cat strace.log | grep stat
  - strace ./node_modules/.bin/tsc -p good-test-case/proj1/tsconfig.json &> strace-good.log
  - cat strace-good.log | grep stat